// Lays out the parsed report into fixed-size PDF pages (content-stream
// command strings), paginating whenever a page's text runs out of room.

import type { ApiReport } from "../../lib/api";
import { parseReportMarkdown } from "./pdfMarkdown";
import { cleanPdfText, shortId, textCommand, truncateText, wrapText } from "./pdfPrimitives";

type PdfTextBlock = {
  text: string;
  size?: number;
  font?: "regular" | "bold";
  color?: [number, number, number];
  indent?: number;
  gapBefore?: number;
  maxChars?: number;
};

type ParsedReport = ReturnType<typeof parseReportMarkdown>;

export function layoutReportPages(report: ApiReport, parsed: ParsedReport) {
  const pages: string[] = [];
  let commands = pageHeader(report, parsed.metadata, 1);
  let y = 632;

  const addBlock = (block: PdfTextBlock) => {
    const size = block.size ?? 10;
    const lineHeight = Math.round(size * 1.45);
    y -= block.gapBefore ?? 0;
    const lines = wrapText(cleanPdfText(block.text), block.maxChars ?? (block.indent ? 74 : 86));
    lines.forEach((line) => {
      if (y < 62) {
        commands += pageFooter(pages.length + 1);
        pages.push(commands);
        commands = pageHeader(report, parsed.metadata, pages.length + 1);
        y = 632;
      }
      commands += textCommand(line, 54 + (block.indent ?? 0), y, size, block.font ?? "regular", block.color ?? [0.12, 0.16, 0.23]);
      y -= lineHeight;
    });
  };

  addExecutiveSummary(addBlock, parsed);
  addVisibleSections(addBlock, parsed);
  addReferences(addBlock, parsed);
  addClosingSummary(addBlock, parsed);

  commands += pageFooter(pages.length + 1);
  pages.push(commands);
  return pages;
}

function addExecutiveSummary(addBlock: (block: PdfTextBlock) => void, parsed: ParsedReport) {
  addBlock({text: "Executive Summary", size: 15, font: "bold", gapBefore: 0, maxChars: 70});
  addBlock({text: executiveSummary(parsed), size: 10, color: [0.24, 0.29, 0.38], maxChars: 88});
}

function addVisibleSections(addBlock: (block: PdfTextBlock) => void, parsed: ParsedReport) {
  visibleSections(parsed).forEach((section) => {
    addBlock({text: section.title, size: 13, font: "bold", gapBefore: 12, maxChars: 76});
    section.lines.slice(0, section.title.toLowerCase() === "top risk drivers" ? 5 : 7).forEach((line) =>
      addBlock({text: `- ${line}`, size: 9.5, indent: 10, color: [0.22, 0.27, 0.35], maxChars: 82})
    );
  });
}

function addReferences(addBlock: (block: PdfTextBlock) => void, parsed: ParsedReport) {
  addBlock({text: "References", size: 13, font: "bold", gapBefore: 12});
  if (parsed.references.length) {
    parsed.references.forEach((reference) =>
      addBlock({
        text: `[${reference.id}] ${reference.label}: ${reference.detail}`,
        size: 8.7,
        indent: 10,
        color: [0.23, 0.29, 0.39],
        maxChars: 84
      })
    );
  } else {
    addBlock({text: "No references were cited in this run.", size: 9.5, indent: 10, color: [0.35, 0.39, 0.47]});
  }
}

function addClosingSummary(addBlock: (block: PdfTextBlock) => void, parsed: ParsedReport) {
  addBlock({text: "Closing Summary", size: 13, font: "bold", gapBefore: 12});
  addBlock({text: finalSummary(parsed), size: 10, color: [0.22, 0.27, 0.35], maxChars: 88});
}

function visibleSections(parsed: ParsedReport) {
  const allowed = ["top risk drivers", "assets and monitoring", "recommended actions", "limitations"];
  return parsed.sections.filter((section) => allowed.includes(section.title.toLowerCase()));
}

function pageHeader(report: ApiReport, metadata: ParsedReport["metadata"], pageNumber: number) {
  const generated = new Date(report.created_at).toLocaleString("en-AU");
  const region = truncateText(metadata.region, 42);
  const risk = truncateText(metadata.risk, 26);
  return [
    "0.06 0.10 0.18 rg 0 686 612 106 re f",
    "0.95 0.35 0.10 rg 42 730 34 34 re f",
    textCommand("WO", 50, 741, 12, "bold", [1, 1, 1]),
    textCommand("Wildfire Ops", 88, 758, 10, "bold", [0.89, 0.93, 0.98]),
    textCommand("Daily Wildfire", 88, 738, 19, "bold", [1, 1, 1]),
    textCommand("Operations Brief", 88, 717, 19, "bold", [1, 1, 1]),
    "0.10 0.15 0.25 rg 370 708 198 48 re f",
    textCommand(`Region: ${region}`, 384, 746, 8, "regular", [0.88, 0.92, 0.97]),
    textCommand(`Risk: ${risk}`, 384, 730, 9, "bold", [1, 0.90, 0.72]),
    textCommand(`Generated: ${generated}`, 384, 714, 7.7, "regular", [0.78, 0.84, 0.92]),
    "0.93 0.96 1 rg 42 656 528 22 re f",
    textCommand(`Report ${shortId(report.report_id)}  |  Run ${shortId(metadata.runId)}  |  Page ${pageNumber}`, 54, 663, 8.3, "regular", [0.25, 0.32, 0.44])
  ].join("\n");
}

function pageFooter(pageNumber: number) {
  return [
    "0.86 0.89 0.94 RG 42 42 m 570 42 l S",
    textCommand("Generated by Wildfire Ops Copilot. Operational intelligence only; verify before external action.", 42, 26, 8, "regular", [0.42, 0.47, 0.56]),
    textCommand(`Page ${pageNumber}`, 540, 26, 8, "regular", [0.42, 0.47, 0.56])
  ].join("\n");
}

function executiveSummary(parsed: ParsedReport) {
  const recommendations = parsed.sections.find((section) => section.title.toLowerCase() === "recommended actions")?.lines ?? [];
  const firstRecommendation = (recommendations[0] ?? "Continue monitoring the selected AOI and review evidence before external action.").replace(/[.]+$/, "");
  const referenceText = parsed.references.length ? ` Supporting evidence is cited in References R1-R${parsed.references.length}.` : "";
  return `${parsed.metadata.region} is assessed at ${parsed.metadata.risk}. Primary operator focus: ${firstRecommendation}.${referenceText}`;
}

function finalSummary(parsed: ParsedReport) {
  const referenceCount = parsed.references.length;
  return `Use this brief as the operational handoff for the current run. Prioritize recommended monitoring, refresh live hotspot and weather evidence before external action, and treat ${referenceCount} reference${referenceCount === 1 ? "" : "s"} as supporting context rather than official public warning material.`;
}
